In [22]:
#importing necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets  
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import  DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import classification_report
from sklearn import preprocessing

In [23]:
df=pd.read_csv('E:\\Fraud_check.csv')
df.head()

Undergrad Marital.Status  Taxable.Income  City.Population  Work.Experience  \
0        NO         Single           68833            50047               10   
1       YES       Divorced           33700           134075               18   
2        NO        Married           36925           160205               30   
3       YES         Single           50190           193264               15   
4        NO        Married           81002            27533               28   

  Urban  
0   YES  
1   YES  
2   YES  
3   YES  
4    NO

In [24]:
##Converting the Taxable income variable to bucketing. 
df["income"]="<=30000"
df.loc[df["Taxable.Income"]>=30000,"income"]="Good"
df.loc[df["Taxable.Income"]<=30000,"income"]="Risky"

In [25]:
#Droping the Taxable income variable
df.drop(["Taxable.Income"],axis=1,inplace=True)

In [26]:
from sklearn import preprocessing
label_encoder=preprocessing.LabelEncoder()
df['Marital.Status']=label_encoder.fit_transform(df['Marital.Status'])
df['Marital.Status'].unique()

array([2, 0, 1])

In [27]:
df['Undergrad']=label_encoder.fit_transform(df['Undergrad'])
df['Undergrad'].unique()

array([0, 1])

In [28]:
df['Urban']=label_encoder.fit_transform(df['Urban'])
df['Urban'].unique()

array([1, 0])

In [29]:
## Collecting the column names
colnames = list(df.columns)
predictors = colnames[0:5]
target = colnames[5]
##Splitting the data into train and test

In [30]:
x=df[predictors]
y=df[target]

In [31]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_jobs=2,oob_score=True,n_estimators=1000,criterion='entropy')
rf.fit(x,y)

RandomForestClassifier(criterion='entropy', n_estimators=1000, n_jobs=2,
                       oob_score=True)

In [32]:
df['rf_pred']=rf.predict(x)

In [33]:
from sklearn.metrics import confusion_matrix
confusion_matrix(df['income'],df['rf_pred'])

array([[476,   0],
       [  0, 124]], dtype=int64)

In [21]:
target

'income'